version: '3'

services:

  shard1s1:
    container_name: shard1s1
    image: mongo
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db --bind_ip 0.0.0.0
    ports:
      - 50001:27017
    volumes:
      - shard1s1:/data/db

  shard1s2:
    container_name: shard1s2
    image: mongo
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db --bind_ip 0.0.0.0
    ports:
      - 50002:27017
    volumes:
      - shard1s2:/data/db


volumes:
  shard1s1: {}
  shard1s2: {}

# rs.initiate(
#   {
#     _id: "shard1rs",
#     members: [
#       { _id : 0, host : "192.168.0.100:50001" },
#       { _id : 1, host : "192.168.0.100:50002" }
#     ]
#   }
# )