name: HelloWorld

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  workflow_dispatch:
    
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testing
        run: cd Prob && go test validatebst.go validatebst_test.go
        shell: bash

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbyeworld
        run: echo "good bye world"
        shell: bash
